### ISSUE TITLE
Does work with 4.10 but not in 4.13 (chrome)

### ISSUE THREAD

**Issue by ice09** [weijiekoh/eip712-signing-demo#1]
Console shows RPC error.

Can be reproduced by installing both extensions and switching between them, each time reloading the site.

**Comment by weijiekoh** [comment]
https://github.com/MetaMask/metamask-extension/releases

> Equivalent to Version 4.11.1, published as a rollback of bugs introduced in 4.12.0, to ensure a stable public build over the weekend of the EthSanFrancisco hackathon. Participants interested in building on top of the signTypedData signature method should download a custom build as described in this article.

Yeah, MetaMask just rolled back to 4.11.1 (which is in turn a revert to 4.9.3).

**Comment by ice09** [comment]
Ok, will go with the 4.10 then, thanks for the quick reply.
